// <auto-generated />
using System;
using Claim_Form.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Claim_Form.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318140542_TravelModelUpdate")]
    partial class TravelModelUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Claim_Form.Entities.CashInfo", b =>
                {
                    b.Property<Guid>("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("INRRate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalLoaded")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("CashInfo");
                });

            modelBuilder.Entity("Claim_Form.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CostCenter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VenderCost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpCode")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Claim_Form.Entities.Expense", b =>
                {
                    b.Property<Guid>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Particulars")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecentClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Screenshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportingNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExpenseId");

                    b.HasIndex("RecentClaimId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Claim_Form.Entities.RecentClaim", b =>
                {
                    b.Property<Guid>("RecentClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecentClaimId");

                    b.HasIndex("EmpId");

                    b.ToTable("RecentClaims");
                });

            modelBuilder.Entity("Claim_Form.Entities.TravelDetails", b =>
                {
                    b.Property<Guid>("TravelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrecncyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecentClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TotalDays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TravelEndDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TravelStartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TravelID");

                    b.HasIndex("RecentClaimId")
                        .IsUnique();

                    b.ToTable("TravelDetails");
                });

            modelBuilder.Entity("Claim_Form.Entities.CashInfo", b =>
                {
                    b.HasOne("Claim_Form.Entities.TravelDetails", "TravelDetails")
                        .WithMany("CardCashEntries")
                        .HasForeignKey("id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelDetails");
                });

            modelBuilder.Entity("Claim_Form.Entities.Expense", b =>
                {
                    b.HasOne("Claim_Form.Entities.RecentClaim", "RecentClaim")
                        .WithMany("Expenses")
                        .HasForeignKey("RecentClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecentClaim");
                });

            modelBuilder.Entity("Claim_Form.Entities.RecentClaim", b =>
                {
                    b.HasOne("Claim_Form.Entities.Employee", "Employee")
                        .WithMany("RecentClaims")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Claim_Form.Entities.TravelDetails", b =>
                {
                    b.HasOne("Claim_Form.Entities.RecentClaim", "RecentClaim")
                        .WithOne("TravelDetails")
                        .HasForeignKey("Claim_Form.Entities.TravelDetails", "RecentClaimId");

                    b.Navigation("RecentClaim");
                });

            modelBuilder.Entity("Claim_Form.Entities.Employee", b =>
                {
                    b.Navigation("RecentClaims");
                });

            modelBuilder.Entity("Claim_Form.Entities.RecentClaim", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("TravelDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("Claim_Form.Entities.TravelDetails", b =>
                {
                    b.Navigation("CardCashEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
